"""Shared library for agent-search."""

from agent_common.prompts import (
    ANSWER_SYSTEM,
    ANSWER_SYSTEM_FACTOID,
    ANSWER_SYSTEM_WITH_TOOLS,
    ANSWER_SYSTEM_WITH_TOOLS_FACTOID,
    ANSWER_USER,
    ANSWER_USER_FACTOID,
    FACT_QUERIES_SYSTEM,
    FACT_QUERIES_USER,
    FACTOID_REWRITE_SYSTEM,
    FACTOID_REWRITE_USER,
    HYDE_SYSTEM,
    HYDE_USER,
    KEYWORD_QUERIES_SYSTEM,
    KEYWORD_QUERIES_USER,
    PLAN_SYSTEM,
    PLAN_USER,
)
from agent_common.retrieval import (
    adaptive_k_cutoff,
    build_context,
    context_from_hits,
    merge_hits,
    quality_is_poor,
    sources_from_context,
    strip_thinking,
)
from agent_common.events import EventType
from agent_common.tools import run_calculator, run_execute_code

__all__ = [
    "ANSWER_SYSTEM",
    "ANSWER_SYSTEM_FACTOID",
    "ANSWER_SYSTEM_WITH_TOOLS",
    "ANSWER_SYSTEM_WITH_TOOLS_FACTOID",
    "ANSWER_USER",
    "ANSWER_USER_FACTOID",
    "FACT_QUERIES_SYSTEM",
    "FACT_QUERIES_USER",
    "FACTOID_REWRITE_SYSTEM",
    "FACTOID_REWRITE_USER",
    "HYDE_SYSTEM",
    "HYDE_USER",
    "KEYWORD_QUERIES_SYSTEM",
    "KEYWORD_QUERIES_USER",
    "PLAN_SYSTEM",
    "PLAN_USER",
    "adaptive_k_cutoff",
    "quality_is_poor",
    "merge_hits",
    "build_context",
    "context_from_hits",
    "sources_from_context",
    "strip_thinking",
    "EventType",
    "run_calculator",
    "run_execute_code",
]
